___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [32]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [11]:
my_list=[5,10,15,20,25]

arr = np.array(my_list)
arr

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array of 5x5 with zeros 

In [8]:
zeros = np.zeros((5,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array of 4x4 with ones and assign data type as int

In [10]:
ones = np.ones((4,4),dtype=int)
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [16]:
ones_sevens = np.ones((4,4),dtype=int)+6
ones_sevens

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create thr previous array above by full() method

In [7]:
sevens = np.full((4,4),7,dtype=int)
sevens

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 (inclusive) 

In [18]:
arr = np.arange(2,17,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive)

In [19]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace

In [20]:
np.linspace(0,24,25,dtype=int).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create randomly 5 numbers with numpy

In [21]:
np.random.rand(5)

array([0.9499846 , 0.61800292, 0.26472326, 0.12547786, 0.43480329])

#### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution

In [33]:
x= np.random.randn(5,5)
x

array([[-0.20858084,  1.26210924,  1.43077299,  0.23112043, -1.75983286],
       [ 0.7421507 , -0.0070753 ,  0.23694825,  0.33866948, -0.64143546],
       [-1.21506596, -1.34819806, -0.1615001 , -0.62117125, -2.16959731],
       [-0.47900523, -1.89759958,  0.24503491,  0.87113652,  2.22893092],
       [-1.63277102, -0.60620881,  0.01467799,  0.11320952,  1.39613667]])

In [27]:
x.mean()

0.14626667011598354

In [28]:
np.median(x), np.percentile(x, 50)

(0.2747272648369828, 0.2747272648369828)

In [29]:
x.std(), np.sqrt(x.var())

(0.8085030586247404, 0.8085030586247404)

#### 12. Create a 3*4 array of random int numbers between 20 and 50

In [25]:
np.random.randint(20,50,(3,4))

array([[32, 35, 39, 29],
       [23, 27, 48, 20],
       [42, 25, 47, 43]])

#### 13. Reshape the array below with the shape of 6x8

In [35]:
ranarr = np.random.randint(0,53,size=48)

In [36]:
ranarr

array([ 9, 22, 49, 12, 48, 29,  7, 17, 39, 52, 33, 23, 51, 28, 31, 28, 39,
        7, 15, 39, 45, 52, 48,  4,  1, 50, 44, 25, 52, 14,  9, 15,  5, 34,
        4,  5, 47, 34, 21, 17, 21,  5, 24, 40, 20, 23, 22, 10])

In [37]:
ranarr.reshape(6,8)

array([[ 9, 22, 49, 12, 48, 29,  7, 17],
       [39, 52, 33, 23, 51, 28, 31, 28],
       [39,  7, 15, 39, 45, 52, 48,  4],
       [ 1, 50, 44, 25, 52, 14,  9, 15],
       [ 5, 34,  4,  5, 47, 34, 21, 17],
       [21,  5, 24, 40, 20, 23, 22, 10]])

In [39]:
ranarr.reshape(4,-1)

array([[ 9, 22, 49, 12, 48, 29,  7, 17, 39, 52, 33, 23],
       [51, 28, 31, 28, 39,  7, 15, 39, 45, 52, 48,  4],
       [ 1, 50, 44, 25, 52, 14,  9, 15,  5, 34,  4,  5],
       [47, 34, 21, 17, 21,  5, 24, 40, 20, 23, 22, 10]])

## Numpy Indexing and Selection


In [41]:
#Create array below
mat=np.arange(1,17).reshape(4,4)
mat


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Using the array above, write a code that reproduces the output shown below.<br>

In [42]:
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array above.

In [43]:
mat[:,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [44]:
mat[1,0::2]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [28]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [45]:
mat[:,2]=77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [52]:
mat[[1,3],[0,1]]

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [53]:
mat[1:4:2,0:4:2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [54]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [58]:
mat[mat<10]

array([1, 2, 4, 5, 6, 8, 9])

In [59]:
mat[mat>12]

array([77, 77, 77, 13, 14, 77, 16])

In [60]:
matplus = mat[mat<10]+mat[mat>12]
matplus

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [62]:
np.std(matplus)

29.700546274093877

#### 22. Get the sum of the second column from array above

In [63]:
#print array here
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [66]:
mat[::,1].sum()

32

#### 23. Get the median, mean and std of 3rd row from array above

In [73]:
mat=np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [74]:
mat[2]

array([ 9, 10, 11, 12])

In [75]:
#median
np.median(mat[2])

10.5

In [76]:
#mean
mat[2].mean()

10.5

In [77]:
#std
mat[2].std()

1.118033988749895

# Pandas Section

In [2]:
import pandas as pd

**Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements**

In [3]:
sal=pd.read_csv('Salaries.csv')

In [80]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [81]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [82]:
sal.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

**How many different year values are there?**

In [13]:
sal.groupby("Year")["Year"].count()


Year
2011    36159
2012    36766
2013    37606
2014    38123
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [40]:
#max
max_totalypay = sal["TotalPay"].max()
max_totalypay 

567595.43

In [41]:
#avg
avg_totalpay = sal["TotalPay"].mean()
avg_totalpay 

74768.321971703

**How many records in the TotalPay column are there bigger than avg TotalPay**

In [42]:
len(sal[sal['TotalPay']> avg_totalpay])

69489

**How much does ALBERT PARDINI make (including benefits)?**

In [43]:
employee_Albert = sal[sal['EmployeeName'] =='ALBERT PARDINI']
employee_Albert 

Id    EmployeeName                         JobTitle    BasePay  \
2   3  ALBERT PARDINI  CAPTAIN III (POLICE DEPARTMENT)  212739.13   

   OvertimePay  OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  Notes  \
2    106088.18   16452.6       NaN  335279.91         335279.91  2011    NaN   

          Agency  Status  
2  San Francisco     NaN

In [45]:
employee_Albert['TotalPayBenefits'] 

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is the lowest paid person?**

In [46]:
sal[['EmployeeName','TotalPay']]

EmployeeName   TotalPay
0          NATHANIEL FORD  567595.43
1            GARY JIMENEZ  538909.28
2          ALBERT PARDINI  335279.91
3       CHRISTOPHER CHONG  332343.61
4         PATRICK GARDNER  326373.19
...                   ...        ...
148649      Roy I Tillery       0.00
148650       Not provided       0.00
148651       Not provided       0.00
148652       Not provided       0.00
148653          Joe Lopez    -618.13

[148654 rows x 2 columns]

In [47]:
sal[['EmployeeName','TotalPay']][sal['TotalPay']== sal["TotalPay"].min()]

EmployeeName  TotalPay
148653    Joe Lopez   -618.13

In [48]:
x = sal[sal['TotalPay']== sal["TotalPay"].min()]
x

Id EmployeeName                    JobTitle  BasePay  OvertimePay  \
148653  148654    Joe Lopez  Counselor, Log Cabin Ranch      0.0          0.0   

        OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  Notes  \
148653   -618.13       0.0   -618.13           -618.13  2014    NaN   

               Agency  Status  
148653  San Francisco     NaN

In [49]:
x.loc[:,'EmployeeName']

148653    Joe Lopez
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

In [16]:
sal.JobTitle.unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 the least common Jobs**

In [50]:
sal['JobTitle'].value_counts()

Transit Operator                                  7036
Special Nurse                                     4389
Registered Nurse                                  3736
Public Svc Aide-Public Works                      2518
Police Officer 3                                  2421
                                                  ... 
CHIEF HOUSING INSPECTOR                              1
TRAFFIC SIGNAL OPERATOR                              1
COURT COMPUTER FACILITIES COORDINATOR                1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I       1
VICTIM & WITNESS TECHNICIAN                          1
Name: JobTitle, Length: 2159, dtype: int64

In [51]:
sal['JobTitle'].value_counts().tail(3)

COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012?**

In [52]:
sal.head(2)

Id    EmployeeName                                        JobTitle  \
0   1  NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2    GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN

In [53]:
year_2012 = sal[sal['Year'] == 2012]   
year_2012

Id        EmployeeName                      JobTitle    BasePay  \
36159  36160      Gary Altenberg  Lieutenant, Fire Suppression  128808.87   
36160  36161        Gregory Suhr               Chief of Police  302578.00   
36161  36162          Khoa Trinh   Electronic Maintenance Tech  111921.00   
36162  36163  Joanne Hayes-White        Chief, Fire Department  296943.01   
36163  36164   Frederick Binkley     EMT/Paramedic/Firefighter  126863.19   
...      ...                 ...                           ...        ...   
72920  72921    Charles Williams                  Junior Clerk     -30.58   
72921  72922        John Carajan               General Laborer       0.00   
72922  72923         John Draper                         Clerk      -9.50   
72923  72924        Cherise Wong                 Special Nurse       0.00   
72924  72925        Donald Clark              Transit Operator       0.00   

       OvertimePay  OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
36159    220909.48  13126.31  44430.12  362844.66         407274.78  2012   
36160         0.00  18974.11  69810.19  321552.11         391362.30  2012   
36161    146415.32  78057.41  53102.29  336393.73         389496.02  2012   
36162         0.00  17816.59  72047.88  314759.60         386807.48  2012   
36163    192424.49  17917.18  44438.25  337204.86         381643.11  2012   
...            ...       ...       ...        ...               ...   ...   
72920        45.87      0.00      1.36      15.29             16.65  2012   
72921         0.00      0.00     12.90       0.00             12.90  2012   
72922        14.25      0.00      0.42       4.75              5.17  2012   
72923         0.00      3.28      0.88       3.28              4.16  2012   
72924         0.00      1.77      0.14       1.77              1.91  2012   

       Notes         Agency  Status  
36159    NaN  San Francisco     NaN  
36160    NaN  San Francisco     NaN  
36161    NaN  San Francisco     NaN  
36162    NaN  San Francisco     NaN  
36163    NaN  San Francisco     NaN  
...      ...            ...     ...  
72920    NaN  San Francisco     NaN  
72921    NaN  San Francisco     NaN  
72922    NaN  San Francisco     NaN  
72923    NaN  San Francisco     NaN  
72924    NaN  San Francisco     NaN  

[36766 rows x 13 columns]

In [54]:
year_2012[year_2012['TotalPayBenefits']  >( sal['TotalPayBenefits'].mean()) ] 

Id        EmployeeName                      JobTitle    BasePay  \
36159  36160      Gary Altenberg  Lieutenant, Fire Suppression  128808.87   
36160  36161        Gregory Suhr               Chief of Police  302578.00   
36161  36162          Khoa Trinh   Electronic Maintenance Tech  111921.00   
36162  36163  Joanne Hayes-White        Chief, Fire Department  296943.01   
36163  36164   Frederick Binkley     EMT/Paramedic/Firefighter  126863.19   
...      ...                 ...                           ...        ...   
56520  56521        Sue Madrigal     Senior Eligibility Worker   63841.94   
56521  56522   Concepcion Gruber                   Secretary 2   61996.06   
56522  56523         Kerman Chan       Parking Control Officer   55358.50   
56523  56524      Ramon Lafuente       Parking Control Officer   56006.80   
56524  56525      Lai Ping Szeto            Eligibility Worker   61253.05   

       OvertimePay  OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
36159    220909.48  13126.31  44430.12  362844.66         407274.78  2012   
36160         0.00  18974.11  69810.19  321552.11         391362.30  2012   
36161    146415.32  78057.41  53102.29  336393.73         389496.02  2012   
36162         0.00  17816.59  72047.88  314759.60         386807.48  2012   
36163    192424.49  17917.18  44438.25  337204.86         381643.11  2012   
...            ...       ...       ...        ...               ...   ...   
56520         0.00    568.66  29305.51   64410.60          93716.11  2012   
56521      1111.50    624.00  29981.74   63731.56          93713.30  2012   
56522      8539.77   1231.25  28579.83   65129.52          93709.35  2012   
56523      6326.45   2175.24  29192.61   64508.49          93701.10  2012   
56524       988.54   1460.00  29996.77   63701.59          93698.36  2012   

       Notes         Agency  Status  
36159    NaN  San Francisco     NaN  
36160    NaN  San Francisco     NaN  
36161    NaN  San Francisco     NaN  
36162    NaN  San Francisco     NaN  
36163    NaN  San Francisco     NaN  
...      ...            ...     ...  
56520    NaN  San Francisco     NaN  
56521    NaN  San Francisco     NaN  
56522    NaN  San Francisco     NaN  
56523    NaN  San Francisco     NaN  
56524    NaN  San Francisco     NaN  

[20366 rows x 13 columns]

In [55]:
year_2012[year_2012['TotalPayBenefits']  >( sal['TotalPayBenefits'].mean())].shape[0]

20366

**How many people have a title of Manager in their jobs?**

In [59]:
#use apply function here
def title_manager(x):
    if "Manager".casefold() in x.casefold():
        return True
    else:
        return False 

sal[sal['JobTitle'].apply(title_manager)].shape[0]

4110

**Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe**

In [60]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [61]:
sal_new= sal.iloc[:,[0,1,2,7,8]]
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

**Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df** 

In [62]:
sal_new=sal.loc[:,'EmployeeName':'TotalPayBenefits'] 
sal_new

EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

          BasePay  OvertimePay   OtherPay  Benefits   TotalPay  \
0       167411.18         0.00  400184.25       NaN  567595.43   
1       155966.02    245131.88  137811.38       NaN  538909.28   
2       212739.13    106088.18   16452.60       NaN  335279.91   
3        77916.00     56120.71  198306.90       NaN  332343.61   
4       134401.60      9737.00  182234.59       NaN  326373.19   
...           ...          ...        ...       ...        ...   
148649       0.00         0.00       0.00       0.0       0.00   
148650        NaN          NaN        NaN       NaN       0.00   
148651        NaN          NaN        NaN       NaN       0.00   
148652        NaN          NaN        NaN       NaN       0.00   
148653       0.00         0.00    -618.13       0.0    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 8 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [64]:
df = sal[(sal['TotalPayBenefits'].mean()>sal['TotalPayBenefits']) &( sal['TotalPayBenefits'] > sal['TotalPayBenefits'].min())]
df['EmployeeName']

10806            KWE LEE
10807     MIGUEL CARO JR
10808      JOANNE MORRIS
10809      LAYLA WELBORN
10810            LE BANH
               ...      
148648       Leon Walker
148649     Roy I Tillery
148650      Not provided
148651      Not provided
148652      Not provided
Name: EmployeeName, Length: 75649, dtype: object

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___